---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170609011313"
editor:
  name: "PrepareTravisBuildFiles"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.4.7"
  parameters:
    - "project": "mendehlsson"
    - "owner": "spring-team"
    - "encryptedGithubToken": "O**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedArtifactoryUser": "i**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedArtifactoryToken": "n**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170629070330"
editor:
  name: "CascadeEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.5.8"
  parameters:
    - "script": "{"description":"Cascaded changes from `spring-rest-seed`","steps":[{"description":"update Maven Travis CI configuration","payload":{"updates":"{\"cache\":{\"directories\":[\"$HOME/.m2\"]}}"},"primitive":"UpdateTravisConfigurationEditor"}]}"

